### ISSUE TITLE
gstreamer:some errors

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/moonbase-other#1400]
make[4]: Leaving directory '/usr/src/gstreamer-1.16.2/gst'
make[3]: Leaving directory '/usr/src/gstreamer-1.16.2/gst'
make[2]: Leaving directory '/usr/src/gstreamer-1.16.2/gst'
Making all in libs
make[2]: Entering directory '/usr/src/gstreamer-1.16.2/libs'
Making all in gst
make[3]: Entering directory '/usr/src/gstreamer-1.16.2/libs/gst'
Making all in base
make[4]: Entering directory '/usr/src/gstreamer-1.16.2/libs/gst/base'
  CC       libgstbase_1.0_la-gstadapter.lo
  CC       libgstbase_1.0_la-gstaggregator.lo
  CC       libgstbase_1.0_la-gstbaseparse.lo
  CC       libgstbase_1.0_la-gstbasesink.lo
  CC       libgstbase_1.0_la-gstbasesrc.lo
  CC       libgstbase_1.0_la-gstbasetransform.lo
  CC       libgstbase_1.0_la-gstbitreader.lo
  CC       libgstbase_1.0_la-gstbitwriter.lo
  CC       libgstbase_1.0_la-gstbytereader.lo
  CC       libgstbase_1.0_la-gstbytewriter.lo
  CC       libgstbase_1.0_la-gstcollectpads.lo
  CC       libgstbase_1.0_la-gstdataqueue.lo
  CC       libgstbase_1.0_la-gstflowcombiner.lo
  CC       libgstbase_1.0_la-gstpushsrc.lo
  CC       libgstbase_1.0_la-gstqueuearray.lo
  CC       libgstbase_1.0_la-gsttypefindhelper.lo
  CCLD     libgstbase-1.0.la
make[4]: Leaving directory '/usr/src/gstreamer-1.16.2/libs/gst/base'
Making all in controller
make[4]: Entering directory '/usr/src/gstreamer-1.16.2/libs/gst/controller'
  GEN      controller-enumtypes.h
  GEN      controller-enumtypes.c
/usr/bin/make  all-am
make[5]: Entering directory '/usr/src/gstreamer-1.16.2/libs/gst/controller'
  CC       libgstcontroller_1.0_la-gstargbcontrolbinding.lo
  CC       libgstcontroller_1.0_la-gstdirectcontrolbinding.lo
  CC       libgstcontroller_1.0_la-gsttimedvaluecontrolsource.lo
  CC       libgstcontroller_1.0_la-gstinterpolationcontrolsource.lo
  CC       libgstcontroller_1.0_la-gstproxycontrolbinding.lo
  CC       libgstcontroller_1.0_la-gsttriggercontrolsource.lo
  CC       libgstcontroller_1.0_la-gstlfocontrolsource.lo
  CC       libgstcontroller_1.0_la-controller-enumtypes.lo
controller-enumtypes.c:10:1: error: stray '\' in program
   10 | \#include "gstinterpolationcontrolsource.h"
      | ^
controller-enumtypes.c:10:2: error: stray '#' in program
   10 | \#include "gstinterpolationcontrolsource.h"
      |  ^
controller-enumtypes.c:10:11: error: expected '=', ',', ';', 'asm' or '__attribute__' before string constant
   10 | \#include "gstinterpolationcontrolsource.h"
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
controller-enumtypes.c:11:1: error: stray '\' in program
   11 | \#include "gstlfocontrolsource.h"
      | ^
controller-enumtypes.c:11:2: error: stray '#' in program
   11 | \#include "gstlfocontrolsource.h"
      |  ^
controller-enumtypes.c: In function 'gst_lfo_waveform_get_type':
controller-enumtypes.c:39:9: error: 'GST_LFO_WAVEFORM_SINE' undeclared (first use in this function)
   39 |       { GST_LFO_WAVEFORM_SINE, "GST_LFO_WAVEFORM_SINE", "sine" },
      |         ^~~~~~~~~~~~~~~~~~~~~
controller-enumtypes.c:39:9: note: each undeclared identifier is reported only once for each function it appears in
controller-enumtypes.c:40:9: error: 'GST_LFO_WAVEFORM_SQUARE' undeclared (first use in this function)
   40 |       { GST_LFO_WAVEFORM_SQUARE, "GST_LFO_WAVEFORM_SQUARE", "square" },
      |         ^~~~~~~~~~~~~~~~~~~~~~~
controller-enumtypes.c:41:9: error: 'GST_LFO_WAVEFORM_SAW' undeclared (first use in this function)
   41 |       { GST_LFO_WAVEFORM_SAW, "GST_LFO_WAVEFORM_SAW", "saw" },
      |         ^~~~~~~~~~~~~~~~~~~~
controller-enumtypes.c:42:9: error: 'GST_LFO_WAVEFORM_REVERSE_SAW' undeclared (first use in this function)
   42 |       { GST_LFO_WAVEFORM_REVERSE_SAW, "GST_LFO_WAVEFORM_REVERSE_SAW", "reverse-saw" },
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
controller-enumtypes.c:43:9: error: 'GST_LFO_WAVEFORM_TRIANGLE' undeclared (first use in this function)
   43 |       { GST_LFO_WAVEFORM_TRIANGLE, "GST_LFO_WAVEFORM_TRIANGLE", "triangle" },
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~
make[5]: *** [Makefile:780: libgstcontroller_1.0_la-controller-enumtypes.lo] Error 1
make[5]: Leaving directory '/usr/src/gstreamer-1.16.2/libs/gst/controller'
make[4]: *** [Makefile:612: all] Error 2
make[4]: Leaving directory '/usr/src/gstreamer-1.16.2/libs/gst/controller'
make[3]: *** [Makefile:553: all-recursive] Error 1
make[3]: Leaving directory '/usr/src/gstreamer-1.16.2/libs/gst'
make[2]: *** [Makefile:548: all-recursive] Error 1
make[2]: Leaving directory '/usr/src/gstreamer-1.16.2/libs'
make[1]: *** [Makefile:742: all-recursive] Error 1
make[1]: Leaving directory '/usr/src/gstreamer-1.16.2'
make: *** [Makefile:648: all] Error 2
Creating /var/log/lunar/compile/gstreamer-1.16.2.xz

**Comment by v4hn** [comment]
I just started debugging meson's gnome module before I even noticed our build does not even use meson yet.
It looks like they broke their autotools build with a superfluous `\`.

**Comment by v4hn** [comment]
I just pushed a migration to meson.

**Comment by lhw828** [comment]
> I just pushed a migration to meson.

gst-plugins-base has the same errors.I think gst-plugins-bad ,too.

@v4hn 

make[4]: Leaving directory '/usr/src/gst-plugins-base-1.16.2/gst-libs/gst/fft'
  CC       libgstvideo_1.0_la-video-resampler.lo
  CC       libgstvideo_1.0_la-video-blend.lo
  CC       libgstvideo_1.0_la-video-overlay-composition.lo
  CC       libgstvideo_1.0_la-video-multiview.lo
  CC       libgstvideo_1.0_la-gstvideotimecode.lo
  CC       libgstvideo_1.0_la-tmp-orc.lo
  CC       libgstvideo_1.0_la-video-enumtypes.lo
video-enumtypes.c:10:1: error: stray '\' in program
   10 | \#include "video.h"
      | ^
video-enumtypes.c:10:2: error: stray '#' in program
   10 | \#include "video.h"
      |  ^
video-enumtypes.c:10:11: error: expected '=', ',', ';', 'asm' or '__attribute__' before string constant
   10 | \#include "video.h"
      |           ^~~~~~~~~
video-enumtypes.c:11:1: error: stray '\' in program
   11 | \#include "video-format.h"
      | ^
video-enumtypes.c:11:2: error: stray '#' in program
   11 | \#include "video-format.h"
      |  ^
video-enumtypes.c:12:1: error: stray '\' in program
   12 | \#include "video-color.h"
      | ^
video-enumtypes.c:12:2: error: stray '#' in program
   12 | \#include "video-color.h"
      |  ^
video-enumtypes.c:13:1: error: stray '\' in program
   13 | \#include "video-info.h"
      | ^
video-enumtypes.c:13:2: error: stray '#' in program
   13 | \#include "video-info.h"
      |  ^
video-enumtypes.c:14:1: error: stray '\' in program
   14 | \#include "video-dither.h"
      | ^
video-enumtypes.c:14:2: error: stray '#' in program
   14 | \#include "video-dither.h"
      |  ^
video-enumtypes.c:15:1: error: stray '\' in program
   15 | \#include "colorbalance.h"
      | ^
video-enumtypes.c:15:2: error: stray '#' in program
   15 | \#include "colorbalance.h"
      |  ^
video-enumtypes.c:16:1: error: stray '\' in program
   16 | \#include "navigation.h"
      | ^
video-enumtypes.c:16:2: error: stray '#' in program
   16 | \#include "navigation.h"
      |  ^
video-enumtypes.c:17:1: error: stray '\' in program
   17 | \#include "video-chroma.h"
      | ^
video-enumtypes.c:17:2: error: stray '#' in program
   17 | \#include "video-chroma.h"
      |  ^
video-enumtypes.c:18:1: error: stray '\' in program
   18 | \#include "video-tile.h"
      | ^
video-enumtypes.c:18:2: error: stray '#' in program
   18 | \#include "video-tile.h"
      |  ^
video-enumtypes.c:19:1: error: stray '\' in program
   19 | \#include "video-converter.h"
      | ^
video-enumtypes.c:19:2: error: stray '#' in program
   19 | \#include "video-converter.h"
      |  ^
video-enumtypes.c:20:1: error: stray '\' in program
   20 | \#include "video-resampler.h"
      | ^
video-enumtypes.c:20:2: error: stray '#' in program
   20 | \#include "video-resampler.h"
      |  ^
video-enumtypes.c:21:1: error: stray '\' in program
   21 | \#include "video-frame.h"
      | ^
video-enumtypes.c:21:2: error: stray '#' in program
   21 | \#include "video-frame.h"
      |  ^
video-enumtypes.c:22:1: error: stray '\' in program
   22 | \#include "video-scaler.h"
      | ^
video-enumtypes.c:22:2: error: stray '#' in program
   22 | \#include "video-scaler.h"
      |  ^
video-enumtypes.c:23:1: error: stray '\' in program
   23 | \#include "video-anc.h"
      | ^
video-enumtypes.c:23:2: error: stray '#' in program
   23 | \#include "video-anc.h"
      |  ^
video-enumtypes.c:24:1: error: stray '\' in program
   24 | \#include "video-overlay-composition.h"
      | ^
video-enumtypes.c:24:2: error: stray '#' in program
   24 | \#include "video-overlay-composition.h"
      |  ^
video-enumtypes.c: In function 'gst_navigation_command_get_type':
video-enumtypes.c:50:9: error: 'GST_NAVIGATION_COMMAND_INVALID' undeclared (first use in this function)
   50 |       { GST_NAVIGATION_COMMAND_INVALID, "GST_NAVIGATION_COMMAND_INVALID", "invalid" },

**Comment by lhw828** [comment]
also and gst-plugins-ugly,gst-plugins-good. @v4hn

**Comment by v4hn** [comment]
I just migrated gst-plugins-base too.

gst-plugins-good and gst-plugins-ugly, compile successfully over here.
gst-plugins-bad still fails.

Feel free to do the same migration I did for gst-plugins-base for the other three in a pull-request!
I don't have any more time available right now...

**Comment by lhw828** [comment]
@florin65 gst-plugins-bad still fails.
I tried to fix it but it still failed,When you have time, help fix this, please.

**Comment by v4hn** [comment]
I just pushed a patch to migrate `gst-plugins-bad` to meson.

The same should be done for `gst-plugins-good` and `gst-plugins-ugly`, but for now they compile at least.

**Comment by florin65** [comment]
The gstreamer and all the gst related modules are build with meson now.
Do use 'lin -rc' for rebuilding it.
